import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElButton from 'element-plus/es/components/button/index'
import ElInput from 'element-plus/es/components/input/index'
import ElSelect from 'element-plus/es/components/select/index'
import { ElOption } from 'element-plus/es/components/select/index'
import ElAlert from 'element-plus/es/components/alert/index'
import 'element-plus/theme-chalk/base.css'
import 'element-plus/theme-chalk/el-button.css'
import 'element-plus/theme-chalk/el-input.css'
import 'element-plus/theme-chalk/el-select.css'
import 'element-plus/theme-chalk/el-option.css'
import 'element-plus/theme-chalk/el-alert.css'
import 'element-plus/theme-chalk/el-popper.css'
import 'element-plus/theme-chalk/el-scrollbar.css'
import 'element-plus/theme-chalk/el-tag.css'
import './style.css'
import App from './App.vue'
const app = createApp(App).use(createPinia())
for (const component of [ElButton, ElInput, ElSelect, ElOption, ElAlert]) app.use(component)
app.mount('#app')
