export interface Session { username: string; csrf_token: string; expires_at: number; demo_enabled: boolean }
export interface ApiErrorData { code: string; safe_message: string; retryable: boolean }
export interface Receipt { operation_id: string; plan_digest: string; committed_at: number; tool: string; changed_records: number; rows: Record<string, unknown>[]; business_state_digest: string; direct_changes: number; cascaded_changes: number }
export interface Operation { id: string; requester: string; resource_id: string; intent: string; tool: string; run_id: string; state: string; decision: string | null; reason_code: string | null; ready_source: string | null; version: number; created_at: number; updated_at: number; expires_at: number; impact: number | null; plan_digest: string | null; result: Receipt | null; error: ApiErrorData | null; poll_after_ms: number | null }
export interface Change { table: string; id: number; kind: string; scope: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null }
export interface Preview { coverage: string; matched_records: number; non_test_matches: number; total_changes: number; direct_changes: number; cascaded_changes: number; changes: Change[]; snapshot_at: number; preview_ms: number; recovery_status: string; limitations: string[]; query_result: Record<string, unknown>[]; covered_tables: string[]; redacted_fields: string[]; business_state_digest: string; schema_digest: string }
export interface Review { operation: Operation; view_id: string | null; view_digest: string | null; view: { schema: string; plan_digest: string; request: Record<string, unknown>; preview: Preview; expires_at: number; principal_id: string; reason_code: string } | null }
export interface Audit { chain_valid: boolean; limitation: string; events: { id: number; seq: number; kind: string; payload: Record<string, unknown>; created_at: number; event_hash: string }[] }
export interface Metrics { states: Record<string, number>; audit_events: number; model_evaluation: string; human_study: string }
export const stateLabels: Record<string, string> = { RECEIVED: '已接收', PREVIEWING: '预检中', READY: '待执行', PENDING_APPROVAL: '等待审批', EXECUTING: '执行中', SUCCEEDED: '执行成功', BLOCKED: '已阻止', REJECTED: '已拒绝', EXPIRED: '已过期', CANCELLED: '已取消', STALE: '计划已失效', UNKNOWN: '结果待核实', FAILED: '执行失败' }
export const toolLabels: Record<string, string> = { 'db.query_rows': '读取数据', 'db.update_rows': '更新数据', 'db.delete_rows': '删除数据' }
export const formatTime = (ms: number) => new Date(ms).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })
